name: ecommerce_app
description: Senior level Flutter e-commerce demo app
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_riverpod: ^2.4.1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true